
services:
  main-applic:
    build:
      context: main-applic
      dockerfile: Dockerfile
    container_name: main-applic_container
    ports:
      - "127.0.0.1:3006:3006"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env
    environment:
      TZ: "Europe/Moscow"
      REDIS_PASSW: "${REDIS_PASSW}"
      NEXT_BASE_PATH: "/ui"
      DATABASE_URL: "${DATABASE_URL}"
      PNPM_HOME: "/root/.pnpm-store"
      CACHE_DIR: "/app/pipeline_cache"
    volumes:
      - ./python-applic/pipeline_cache:/app/pipeline_cache
      # - pnpm_cache:/root/.pnpm-store
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "--max-time", "5", "http://localhost:3006/ui/api/healthcheck"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:1.27.5-alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./main-applic/public/temporary:/opt/files
      - ./log/report:/opt/report
      - ./.htpasswd:/opt/.htpasswd
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    environment:
      TZ: Europe/Moscow
    depends_on:
      main-applic:
        condition: service_healthy
      postgres:
        condition: service_healthy
      prefect-applic:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--timeout=3", "--spider", "http://localhost:80/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  postgres:
    build:
      context: postgres-db
      dockerfile: Dockerfile
    container_name: db_postgres_container
    volumes:
      - database_volume:/var/lib/postgresql/data
      - ./main-applic/prisma:/app
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_DB: "${MY_DB_NAME_DEV}"
      POSTGRES_USER: "${MY_DB_USER_DEV}"
      POSTGRES_PASSWORD: "${MY_DB_PASSWORD_DEV}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "cd / && pg_isready -U ${MY_DB_USER_DEV} -d ${MY_DB_NAME_DEV}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  prefect-applic:
    build: ./python-applic
    container_name: python_app_container
    ports:
      - "127.0.0.1:4200:4200"
    environment:
      TZ: "Europe/Moscow"
      PREFECT_API_URL: "http://127.0.0.1:4200/api"
      PREFECT_UI_API_URL: "http://192.168.1.77/api/python"
      # PREFECT_UI_API_URL: "http://nginx/api/python"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --timeout=5 -O - http://127.0.0.1:4200/api/health | grep -q 'true'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./python-applic/pipeline_cache:/app/pipeline_cache

  redis:
    image: redis:7-alpine
    container_name: redis_container
    environment:
      TZ: "Europe/Moscow"
      REDIS_PASSW: "${REDIS_PASSW}"
    command: ["redis-server", "--requirepass", "${REDIS_PASSW}"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $REDIS_PASSW ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  database_volume:
  # pnpm_cache:
